name: CI Ruuner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install Maven dependencies
      run: mvn clean install --no-transfer-progress

    - name: Run tests
      run: mvn test

    - name: Generate Allure report
      run: mvn allure:report

    - name: Upload Allure results
      uses: actions/upload-artifact@v2
      with:
        name: allure-results
        path: target/allure-results

    - name: Upload Surefire reports
      uses: actions/upload-artifact@v2
      with:
        name: surefire-reports
        path: target/surefire-reports
