name: CI Runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip xvfb
        sudo apt-get install -y google-chrome-stable

    - name: Get Chrome version
      id: chrome-version
      run: |
        google-chrome --version | grep -oE '[0-9.]+' > chrome_version.txt
        CHROME_VERSION=$(cat chrome_version.txt)
        echo "CHROME_VERSION=$CHROME_VERSION" >> $GITHUB_ENV

    - name: Install matching ChromeDriver
      run: |
        CHROME_VERSION=${{ env.CHROME_VERSION }}
        CHROMEDRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        wget -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
        unzip /tmp/chromedriver.zip -d /usr/local/bin/
        rm /tmp/chromedriver.zip

    - name: Install Maven dependencies
      run: mvn clean install --no-transfer-progress

    - name: Run tests
      run: xvfb-run -a mvn test
      continue-on-error: true

    - name: Print test logs
      if: failure()
      run: cat target/surefire-reports/*.txt

    - name: Generate Allure report
      run: mvn allure:report

    - name: Upload Allure results
      uses: actions/upload-artifact@v2
      with:
        name: allure-results
        path: target/allure-results

    - name: Upload Surefire reports
      uses: actions/upload-artifact@v2
      with:
        name: surefire-reports
        path: target/surefire-reports
